---
- hosts: all
  vars:
    http_port: 80
    max_clients: 200
  sudo: yes
  remote_user: ec2-user
  tasks:
  - name: ensure apache is at the latest version
    yum: name=httpd state=latest
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    yum: name=httpd
  handlers:
    - name: restart apache
      yum: name=httpd


                                                                                                         
                                                                                                       
                
